apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "petclinic-service.fullname" . }}-config
  labels:
    {{- include "petclinic-service.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.configMap }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- if .Values.datasource.enabled }}
  SPRING_DATASOURCE_URL: {{ .Values.datasource.url | quote }}
  {{- end }}
