# Module: rds — input variables
# See docs/technical-spec.md#rds-database and #terraform-modules.

variable "project" {
  description = "Project name, used in resource naming."
  type        = string
  default     = "petclinic"
}

variable "environment" {
  description = "Deployment environment (dev or prod)."
  type        = string

  validation {
    condition     = contains(["dev", "prod"], var.environment)
    error_message = "environment must be \"dev\" or \"prod\"."
  }
}

variable "subnet_ids" {
  description = "Subnet IDs for the DB subnet group (public subnets from the vpc module — see ADR-0001; the RDS security group is the access boundary, not subnet placement)."
  type        = list(string)

  validation {
    condition     = length(var.subnet_ids) >= 2
    error_message = "subnet_ids must contain at least 2 subnets in different AZs (RDS DB subnet group requirement)."
  }
}

variable "security_group_id" {
  description = "RDS security group ID (from the vpc module) — allows 3306 from the EKS node SG only."
  type        = string
}

variable "instance_class" {
  description = "RDS instance class."
  type        = string
  default     = "db.t4g.micro"
}

variable "engine_version" {
  description = "MySQL engine version (major.minor — AWS resolves the current default minor release)."
  type        = string
  default     = "8.0"
}

variable "allocated_storage" {
  description = "Initial allocated storage in GB."
  type        = number
  default     = 20
}

variable "max_allocated_storage" {
  description = "Max storage in GB RDS autoscaling can grow to. Must be >= allocated_storage."
  type        = number
  default     = 20

  validation {
    condition     = var.max_allocated_storage >= var.allocated_storage
    error_message = "max_allocated_storage must be >= allocated_storage."
  }
}

variable "multi_az" {
  description = "Multi-AZ deployment. false in both envs — cost optimization for a learning project; enable in real production for automatic failover (see docs/technical-spec.md#rds-database)."
  type        = bool
  default     = false
}

variable "backup_retention_period" {
  description = "Automated backup retention in days (7 for dev, 30 for prod per docs/technical-spec.md#rds-database)."
  type        = number
  default     = 7
}

variable "skip_final_snapshot" {
  description = "Skip final snapshot on destroy (true for dev, false for prod)."
  type        = bool
  default     = true
}

variable "deletion_protection" {
  description = "RDS deletion protection."
  type        = bool
  default     = false
}

variable "master_username" {
  description = "RDS master username. The master password is never accepted as input — it is generated by this module (random_password) and stored only in Secrets Manager (PETPLAT-23)."
  type        = string
  default     = "petclinic"
}

variable "log_retention_days" {
  description = "Retention for the RDS error log CloudWatch log group."
  type        = number
  default     = 30
}

variable "db_name" {
  description = "Initial database name — the single shared petclinic database used by customers/visits/vets services (PETPLAT-24)."
  type        = string
  default     = "petclinic"
}

variable "tags" {
  description = "Additional tags merged into every resource (Project/Environment/ManagedBy come from provider default_tags)."
  type        = map(string)
  default     = {}
}
